FROM debian:buster

#install all the program
RUN apt-get update && \
    apt-get install -y \
    nginx \
    openssl

RUN mkdir -p /etc/nginx/ssl

# Generate SSL certificate
RUN openssl req -newkey rsa:4096 -x509 -sha256 -days 365 -nodes \
    -out /etc/nginx/ssl/jcarlen.crt \
    -keyout /etc/nginx/ssl/jcarlen.key \
    -subj "/C=CH/ST=VD/L=Lausanne/O=42/OU=42/CN=jcarlen.42.fr/UID=jcarlen"

# Copy NGINX configuration
COPY ./conf/nginx.conf /etc/nginx/conf.d

RUN mkdir -p /run/nginx

# Expose port 443 for HTTPS
EXPOSE 443

# Start NGINX
CMD ["nginx", "-g", "daemon off;"]
